In [1]:
import numpy as np

# Creating and Accessing NumPy Arrays

In [2]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [3]:
print(a[0],a[1],a[2],sep="\n")
a[0]=5
print(a)

1
2
3
[5 2 3]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0],b[1,1])
print(b)

(2, 3)
1 2 4 5
[[1 2 3]
 [4 5 6]]


# NumPy Function to Create Arrays

a=np.zeros((2,2))
print(a)

In [5]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [6]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [7]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
e=np.random.random((2,2))
print(e)

[[0.55559562 0.92786525]
 [0.1451634  0.9465998 ]]


In [9]:
f=np.random.randint((2,2),100)
print(f)

[97 59]


# Creating Arrays from Sub-classes

In [10]:
np.array(np.mat('1 2; 3 4'),subok=False)
#np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [11]:
np.array(np.mat('1 2; 3 4'),subok=True)

matrix([[1, 2],
        [3, 4]])

# Array Indexing

In [12]:
a=np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [13]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[...,1])
print(a[...,1:])
print(a[1,...])
print(a[1:,...])

[2 5 8]
[[2 3]
 [5 6]
 [8 9]]
[4 5 6]
[[4 5 6]
 [7 8 9]]


In [15]:
#Integer Indexing
a=np.array([[1,2],[3,4],[5,6]])
b=a[[0,1,2],[0,1,0]]
print(a)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [16]:
#Boolean Indexing
a=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(a[a>5])

[ 6  7  8  9 10 11]
